version: '3.7'

services:

  # grpc.sandbox.service:
  #   image: ghcr.io/level-up-organization/sandbox.grpc.service:latest
  #   container_name: grpc.sandbox.service
  #   environment:
  #     - CsharpSandboxUrl=http://grpc.sandbox.csharp:7778
  #     - ASPNETCORE_ENVIRONMENT=Production
  #   ports:
  #     - "7777:7777"
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=true"
  #   networks:
  #     - level-up-network
  
  # grpc.sandbox.csharp:
  #   image: ghcr.io/level-up-organization/sandbox.csharp.service:latest
  #   container_name: grpc.sandbox.csharp
  #   ports:
  #     - "7778:7778"
  #   networks:
  #     - level-up-network

  frontend.level-up:
    image: ghcr.io/level-up-organization/level-up-frontend:production-latest
    container_name: frontend.level-up 
    ports:
      - "5001:80"
    labels:
       - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - level-up-network

  api.gateway.microservice:
    image: ghcr.io/level-up-organization/api.gateway.microservice:production-latest
    container_name: api.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "7002:8080"
      - "7003:8081"
    labels:
       - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - api.auth.microservice
    #  - api.course.microservice
    networks:
      - level-up-network

  # api.course.microservice:
  #   image: ghcr.io/level-up-organization/api.course.microservice:development-latest
  #   container_name: api.course
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   ports:
  #     - "7004:8082"
  #     - "7005:8083"
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=true"
  #   depends_on:
  #     - redis
  #    ## - graylog
  #   networks:
  #     - level-up-network
  
  api.auth.microservice:
    image: ghcr.io/level-up-organization/api.auth.microservice:production-latest
    container_name: api.auth
    ports:
      - "7006:8080"
      - "7007:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    labels:
       - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - api.auth.db.postgres
     ##- graylog
      - redis
    networks:
      - level-up-network

  api.questions.microservice:
    image: ghcr.io/level-up-organization/api.questions.microservice:production-latest
    container_name: api.questions
    ports:
      - "7009:8080"
    depends_on:
      - api.questions.db.postgres
    labels:
       - "com.centurylinklabs.watchtower.enable=true"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - level-up-network

  # api.payments.microservice:
  #   image: ghcr.io/level-up-organization/api.payments.microservice:production-latest
  #   container_name: api.payments
  #   ports:
  #     - "7010:8080"
  #   depends_on:
  #     - api.payments.db.postgres
  #     - api.auth.microservice
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=true"
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Production
  #     ConnectionStrings__PaymentsDb: Host=api.payments.db.postgres;Port=5432;Database=levelup.payments.microservice;Username=postgres;Password=root
  #     AuthGrpc__Address: http://api.auth.microservice:9092
  #     Pal24__BaseUrl: https://pal24.pro
  #     Pal24__Token: ${PAL24_TOKEN}
  #     Pal24__ShopId: ${PAL24_SHOP_ID}
  #     Pal24__CurrencyIn: RUB
  #   networks:
  #     - level-up-network
    
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9981:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  api.email-service.microservice:
    image: ghcr.io/level-up-organization/email-service-microservice:production-latest
    container_name: api.email-service
    environment:
      - DOTNET_ENVIRONMENT=Production
    labels:
       - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - api.auth.microservice
      - kafka
    networks:
      - level-up-network
    restart: on-failure

  api.outbox-dispatcher.microservice:
    image: ghcr.io/level-up-organization/outbox-dispatcher-microservice:production-latest
    container_name: api.outbox-dispatcher
    environment:
      - DOTNET_ENVIRONMENT=Production
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - api.email-service.microservice
      - api.auth.db.postgres
      - kafka
    networks:
      - level-up-network

  # ------ databases -------
  api.auth.db.postgres:
    container_name: api.auth.db.postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: levelup.auth.microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pg-auth-data:/var/lib/postgresql/data
    networks:
      - level-up-network

  api.questions.db.postgres:
    container_name: api.questions.db.postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: levelup.questions.microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - pg-questions-data:/var/lib/postgresql/data
    networks:
      - level-up-network

  # api.payments.db.postgres:
  #   container_name: api.payments.db.postgres
  #   image: postgres:14
  #   restart: always
  #   environment:
  #     POSTGRES_DB: levelup.payments.microservice
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #   ports:
  #     - "5436:5432"
  #   volumes:
  #     - pg-payments-data:/var/lib/postgresql/data
  #   networks:
  #     - level-up-network
  
  # api.course.db.postgres:
  #   image: postgres:14
  #   restart: always
  #   environment:
  #     POSTGRES_DB: levelup.course.microservice
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #   ports:
  #     - "5431:5432"
  #   volumes:
  #     - pg-course-data:/var/lib/postgresql/data
  #   networks:
  #     - level-up-network

  kafka:
    image: apache/kafka:4.0.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9091
      KAFKA_LISTENERS: CONTROLLER://kafka:9091,PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9093 || exit 1"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s
    volumes:
      - kafka_data_dev:/var/lib/kafka/data
    networks:
      - level-up-network

  kafka-init-topics:
    image: apache/kafka:4.0.1
    container_name: kafka-init-topics
    depends_on:
      - kafka
    networks:
      - level-up-network
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >-
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092
        --create --if-not-exists --topic email-notification-topic
        --partitions 1 --replication-factor 1
        && /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092
        --create --if-not-exists --topic user-registered-topic
        --partitions 1 --replication-factor 1
        && /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092
        --create --if-not-exists --topic user-email-confirmed-topic
        --partitions 1 --replication-factor 1
    restart: "no"


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083
    networks:
      - level-up-network

  # mongo:
  #   image: mongo:5.0
  #   container_name: mongo
  #   restart: unless-stopped
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - graylog

  # opensearch:
  #   image: opensearchproject/opensearch:2.11.1
  #   container_name: opensearch
  #   environment:
  #     - discovery.type=single-node
  #     - plugins.security.disabled=true
  #     - bootstrap.memory_lock=true
  #     - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - opensearch_data:/usr/share/opensearch/data
  #   restart: unless-stopped
  #   networks:
  #     - graylog

  # graylog:
  #   image: graylog/graylog:5.2
  #   container_name: graylog
  #   environment:
  #     - GRAYLOG_PASSWORD_SECRET=admin20041123123123123123123123123123123123123
  #     - GRAYLOG_ROOT_PASSWORD_SHA2=5a50fcee09f9a486b93a63586662a55b10c8108fd74477af42fed8aef4081f5a
  #     - GRAYLOG_HTTP_EXTERNAL_URI=http://81.94.150.219:9000/
  #     - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
  #     - GRAYLOG_MONGODB_URI=mongodb://mongo:27017/graylog
  #   entrypoint: /usr/bin/tini -- wait-for-it mongo:27017 -- wait-for-it opensearch:9200 -- /docker-entrypoint.sh
  #   depends_on:
  #     - mongo
  #     - opensearch
  #   ports:
  #     - "9000:9000"
  #     - "12201:12201/udp"
  #   restart: unless-stopped
  #   volumes:
  #     - graylog_journal:/usr/share/graylog/data/journal
  #   networks:
  #     - graylog
    
  redis:
    image: redis:7
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - level-up-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./auth:/config
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=100
      - WATCHTOWER_LABEL_ENABLE=true
      - REGISTRY_AUTH_FILE=/config/config.json

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx-auth:/etc/nginx/auth
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - api.gateway.microservice
      - frontend.level-up
    networks:
      - level-up-network

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
    networks:
      - level-up-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - level-up-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - level-up-network

networks:
  level-up-network:
    driver: bridge

volumes:
  pg-questions-data:
  #pg-payments-data:
  grafana-storage:
  pg-auth-data:
  nginx-auth:
  # mongo_data:
  # opensearch_data:
  # graylog_journal:
  redis-data:
  # pg-course-data:
  kafka_data_dev:
  portainer_data:
  certbot-etc:
  certbot-var:
  certbot-www:
  zookeeper-data:
